{
 "title": "Speedtest QLv1",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "Letzte Messung !",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Download_MB",
     "query": "SELECT last(\"value\") FROM \"javascript.0.Speedtest.Ergebnisse.Download_MB\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download in MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Download_MB",
     "query": "SELECT last(\"value\") FROM \"javascript.0.Speedtest.Ergebnisse.Download_MB\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "source": "url",
     "type": "json",
     "url": "https://jsonplaceholder.typicode.com/users",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Upload in MB/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Upload_MB",
     "query": "SELECT last(\"value\") FROM \"javascript.0.Speedtest.Ergebnisse.Upload_MB\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download in MBit/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Download_MBit",
     "query": "from(bucket: \"${Bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"javascript.0.Speedtest.Ergebnisse.Download_MBit\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload in MBit/s",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Upload_MBit",
     "query": "SELECT last(\"value\") FROM \"javascript.0.Speedtest.Ergebnisse.Upload_MBit\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speedtest",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Download_MBit",
     "query": "SELECT last(\"value\") FROM \"javascript.0.Speedtest.Ergebnisse.Download_MBit\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Upload_MBit",
     "query": "SELECT last(\"value\") FROM \"javascript.0.Speedtest.Ergebnisse.Upload_MBit\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Ping",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Ping",
     "query": "SELECT last(\"value\") FROM \"javascript.0.Speedtest.Ergebnisse.Ping\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Anzahl Werte pro Tag",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Download_MB",
     "query": "SELECT max(\"value\") FROM \"javascript.0.Speedtest.Ergebnisse.Download_MB\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Durchschnittsdownloadrate in MBit/s",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "Durchschnittsdownloadrate",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "javascript.0.Speedtest.Ergebnisse.Download_MBit",
     "query": "SELECT max(\"value\") FROM \"javascript.0.Speedtest.Ergebnisse.Download_MBit\" WHERE $timeFilter GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}